### ISSUE TITLE
老哥，这个key是什么意思

### ISSUE THREAD

**Issue by oldwang12** [zhangshuai/douyin-go#4]
![Uploading image.png…]()

**Comment by oldwang12** [comment]
![image](https://user-images.githubusercontent.com/67354376/142169391-35d82e30-4eb7-44ce-b3cf-5cfc5a1812e5.png)

**Comment by zhangshuai** [comment]
https://open.douyin.com/platform
在抖音开放平台申请应用后就能找到了
