### ISSUE TITLE
抖音 / 创建视频/上传视频  接口地址升级了

### ISSUE THREAD

**Issue by chinaapus** [zhangshuai/douyin-go#9]
**查询授权账号视频列表**
HTTP URL     https://open.douyin.com/api/douyin/v1/video/video_list/

 **上传视频**
HTTP URL     https://open.douyin.com/api/douyin/v1/video/upload_video/

**就是这个 视频管理/抖音/ 的API地址改了 **
https://developer.open-douyin.com/docs/resource/zh-CN/dop/develop/openapi/video-management/douyin/create-image-text/create-image-text

麻烦您修复一下 我就可以用了 谢谢

**Comment by guaidashu** [comment]
查询特定视频的视频数据接口也变了，震惊
@zhangshuai 
变成  https://open.douyin.com/api/apps/v1/video/query/  了
我看代码里还是 "/api/douyin/v1/video/video_data/"
https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/server/video-id-convert/user-video-data/video-data
